export default [
    { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원'},
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' },
  { img: "https://cdn.purplesto.re/media/store/sale/main_image/ziwipeak_dog_B046DF36_thumb01.png", info: '에어드라이 오타고밸리', weight: '900g', price: '100원' }
]